### PR TITLE
replaced vigour-util/merge calls with lodash equivalent as per #7

### LINKED ISSUE #7: Dependency on deprecated `vigour-util/merge`
When using the config package I get repeated errors in my terminal stating ``WARNING: `vigour-util/merge` is deprecated, consider using `lodash.merge` instead`` as set up by @shawninder in vigour-io/util#4.

### PR DESCRIPTION
**Pull request by tvervest**
fixes #7

### CODE REVIEW

**Comment by shawninder** [comment]
@tvervest I get the feeling you might want `_.merge` instead of `_.assign` (same as assign, but recursive, which is what util/merge did).

Also, for free speed, you can `npm i lodash.assign` (or `npm i lodash.merge`) and `var _assign = require('lodash.assign')` (or `_merge = require('lodash.merge')` ;)

**Comment by tvervest** [comment]
@shawninder I'll change the calls to `_.assign` ;)

Nice tip, that's a cool improvement! :+1: For this module I'll leave it as-is; `lodash` was already a dependency, so I'm not sure what I'll break if I change it :p

**Comment by shawninder** [comment]
@tvervest If you don't remove the lodash dependency, you won't break anything. But of course you don't get the performance benefit either :p

**Comment by tvervest** [comment]
@shawninder

**Comment by shawninder** [comment]
mind:blown

**Comment by marcusbesjes** [comment]
I had some similar work uncommitted on develop :) I made it a pull request to show its slightly different:
#10

**Pull request closed without merging**
